repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
        files: ^backend/
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements
        files: ^backend/
    -   id: check-case-conflict
    -   id: check-docstring-first
        files: ^backend/
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
        files: ^backend/requirements\.txt$
    -   id: check-toml

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.2
    hooks:
    -   id: commitizen
        stages: [commit-msg]
        args: [--allow-abort]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^backend/
    -   id: ruff-format
        files: ^backend/

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        files: ^backend/
        args: [--line-length=88]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    -   id: mypy
        files: ^backend/
        additional_dependencies: [
            types-python-dotenv==1.0.0.20240211,
            pydantic==2.6.1,
            pydantic-settings==2.1.0,
            fastapi==0.109.2
        ]
        args: [--strict, --ignore-missing-imports]
        stages: [pre-push]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    -   id: bandit
        files: ^backend/
        args: ["-c", "pyproject.toml", "-r", "backend/src/"]
        additional_dependencies: ["bandit[toml]"]
        stages: [pre-push]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        additional_dependencies:
        -   "prettier@3.2.5"

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
    -   id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   "eslint@8.56.0"
        -   "eslint-config-prettier@9.1.0"
        -   "eslint-plugin-react@7.33.2"
        -   "eslint-plugin-react-hooks@4.6.0"
        -   "@typescript-eslint/eslint-plugin@6.21.0"
        -   "@typescript-eslint/parser@6.21.0" 