repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: check-toml

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
        args: [--allow-abort]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        stages: [push]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-dotenv==1.0.0.20240211]
        args: [--strict]
        stages: [push]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        additional_dependencies:
        -   "prettier@3.2.5"

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   "eslint@8.56.0"
        -   "eslint-config-prettier@9.1.0"
        -   "eslint-plugin-react@7.33.2"
        -   "eslint-plugin-react-hooks@4.6.0"
        -   "@typescript-eslint/eslint-plugin@6.21.0"
        -   "@typescript-eslint/parser@6.21.0"

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        args: [--rcfile=pyproject.toml]
        stages: [push]
        additional_dependencies: ["pylint[spelling]"] 